version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: detailed
after_build:
- cmd: 7z a release2.zip %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Release\*
before_test:
- cmd: cp -R %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Release %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Debug
artifacts:
- path: release2.zip
  name: release
deploy:
- provider: FTP
  host: web.zone.ee
  protocol: ftp
  username: veebiprojekt
  password:
    secure: rPPevRwz2hIsQcRSogu3fA==
