version: 1.0.{build}
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: 7z a myapp.zip %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Debug\*.dll
artifacts:
- path: myapp.zip
  name: Myapp
deploy:
- provider: FTP
  host: web.zone.ee
  protocol: ftp
  username: veebiprojekt
  password:
    secure: rPPevRwz2hIsQcRSogu3fA==
