version: 1.0.{build}

matrix:
    # first group
    - after_build:
      - cmd: 7z a debug.zip %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Debug\*

    # second group
    - after_build:
      - cmd: 7z a debug.zip %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Release\*

configuration:
- Debug
- Release
before_build:
- cmd: nuget restore
build:
  verbosity: detailed
artifacts:
- path: debug.zip
  name: debug
- path: release.zip
  name: release
deploy:
- provider: FTP
  host: web.zone.ee
  protocol: ftp
  username: veebiprojekt
  password:
    secure: rPPevRwz2hIsQcRSogu3fA==
