version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: detailed
after_build:
- cmd: 7z a release.zip %APPVEYOR_BUILD_FOLDER%\HealthReporter\bin\Release\*
artifacts:
- path: release.zip
  name: release
deploy:
- provider: FTP
  host: web.zone.ee
  protocol: ftp
  username: veebiprojekt
  password:
    secure: rPPevRwz2hIsQcRSogu3fA==
